@WebApi.Test_HostAddress = http://localhost:5240
@host = http://localhost:5240/api
###
GET {{host}}/SqlSugar
###

GET {{host}}/CacheResult
Accept: application/json
###
GET {{host}}/CacheResult
Accept: application/json
###
POST {{host}}/CacheResult/Post
Content-Type: application/json
Idempotency-Key: test

{
    "name": "test"
}
###
GET {{WebApi.Test_HostAddress}}/tests/tests

### 测试sqlsugar
GET {{host}}/SqlSugar/Service
###
GET {{host}}/SqlSugar2/Repository
###
GET {{host}}/SqlSugar/Cache
###
GET {{host}}/SqlSugar/Update
###

### 添加或更新
GET {{WebApi.Test_HostAddress}}/api/sqlsugar/InsertOrUpdate

###
