@WebApi.Test_HostAddress = http://localhost:5000/api

GET {{WebApi.Test_HostAddress}}/CacheResult
Accept: application/json

# POST {{WebApi.Test_HostAddress}}/CacheResult/Post
# Accept: application/json
# //参数
# {
#   "name": ""
# }
###
