@host = http://localhost:5240/api

GET {{host}}/CacheResult
Accept: application/json
###
GET {{host}}/CacheResult
Accept: application/json
###
POST {{host}}/CacheResult/Post
Content-Type: application/json

{
    "name": "test"
}